name: Window Test

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0
          cache: pnpm

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Install app deps
        run: pnpm run postinstall

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
